/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package image_downloader.main;

import image_downloader.http_util.HttpImageStatusCli;

public class App {

    public static void main(String[] args) {
        new HttpImageStatusCli().askStatus();
    }
}
